config/routes.rb
RailsTutIskandar::Application.routes.draw do
  resources :categories
  resources :contents

  root "contents#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :contents
	validates :text, presence: true
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :category
  validates :title, presence: true
  validates :subtitle, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def index
		@categories = Category.all

		respond_to do |format|
			format.html
			format.json {
				output = {
					:success => true,
					:result => @categories
				}

				render json: output
			}
		end
	end

	def new
		@category = Category.new		
	end

	def edit
		@category = Category.find(params[:id])
	end

	def show
		@category = Category.find(params[:id])
	end

	def create
		@category = Category.new(
			params.require(:category).permit(:text)
		)

		if @category.save
			respond_to do |format|
				format.html {
					redirect_to @category
				}

				format.json {
					output = {
						:success => true,
						:result => @category
					}

					render json: output
				}
			end			
		else			
			respond_to do |format|
				format.html {
					render 'new'
				}

				format.json {
					output = {
						:success => false,
						:error => @category.errors.full_messages
					}

					render json: output
				}
			end
		end
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(params.require(:category).permit(:text))			
			format.html {
				redirect_to @category
			}

			format.json {
				output = {
					:success => true,
					:result => @category
				}

				render json: output
			}
		else			
			format.html {
				render 'edit'
			}

			format.json {
				output = {
					:success => false,
					:error => @category.errors.full_messages
				}

				render json: output
			}
		end
	end

	def destroy
		@category = Category.find(params[:id])

		if Content.where(:category_id => params[:id]).update_all('category_id = 1')
			if @category.destroy
				format.html {
					redirect_to categories_path
				}

				format.json {
					output = {
						:success => true
					}

					render json: output
				}
			else
				format.html {
					redirect_to categories_path
				}

				format.json {
					output = {
						:success => false,
						:error => @category.errors.full_messages
					}

					render json: output
				}
			end
		else
			format.html {
				redirect_to categories_path
			}

			format.json {
				output = {
					:success => false,
					:error => 'failed to update dependent'
				}

				render json: output
			}				
		end		
	end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def index
		@contents = Content.all		

		categoryId = params[:category_id]
		if categoryId
			@contents = Content.find(:all, :conditions => {:category_id => categoryId})
		end

		respond_to do |format|
			format.html {
				@categories = Category.all
			}

			format.json {
				output = {
					:success => true,
					:result => @contents
				}

				render json: output
			}
		end
	end

	def new
		@content = Content.new
		@categories = Category.all
	end	

	def edit
		@content = Content.find(params[:id])
		@categories = Category.all
	end

	def show
		@content = Content.find(params[:id])
		@categories = Category.all

		respond_to do |format|
			format.html
			format.json {
				output = {
					:success => true,
					:result => @content
				}

				render json: output
			}
		end
	end

	def create
		@content = Content.new(
			params.require(:content).permit(
				:title,
				:subtitle,
				:category_id,
				:text
			)
		)

		if @content.save
			respond_to do |format|
				format.html {
					redirect_to @content
				}

				format.json {
					output = {
						:success => true,
						:result => @content
					}

					render json: output
				}
			end			
		else			
			respond_to do |format|
				format.html {
					@categories = Category.all
					render 'new'
				}

				format.json {
					output = {
						:success => false,
						:error => @content.errors.full_messages
					}

					render json: output
				}
			end
		end
	end

	def update
		@content = Content.find(params[:id])

		if( @content.update(
				params.require(:content).permit(
					:title,
					:subtitle,
					:category_id,
					:text
				)
			)
		)
			respond_to do |format|
				format.html {
					redirect_to @content
				}

				format.json {
					output = {
						:success => true,
						:result => @content
					}

					render json: output
				}
			end			
		else
			respond_to do |format|
				format.html {
					@categories = Category.all
					render 'edit'
				}

				format.json {
					output = {
						:success => false,
						:error => @content.errors.full_messages
					}
				}
			end			
		end
	end

	def destroy
		@content = Content.find(params[:id])
		
		if @content.destroy
			respond_to do |format|
				format.html {
					redirect_to contents_path
				}

				format.json {
					output = { :success => true }
					render json: output
				}
			end
		else
			respond_to do |format|
				format.html {
					redirect_to contents_path
				}

				format.json {
					output = {
						:success => false,
						:error => @content.errors.full_messages
					}

					render json: output
				}
			end
		end		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |errMsg| %>
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Error!</strong>&nbsp;<%= errMsg %>
		</div>
	<% end %>
<% end %>
<%= form_for @category, :html => { :class => "form-horizontal" } do |f| %>
	<fieldset>
		<div class="form-group">
			<%= f.label :text, class: "control-label" %>
			<%= f.text_field :text, class: "form-control", placeholder: "Category text" %>	
		</div>		
		<div class="form-group" style="text-align: center">
			<%= f.submit class: "btn btn-primary" %>
			<%= link_to "Cancel", categories_path, { class: "btn btn-default" } %>
		</div>
	</fieldset>
<% end %>

app/views/categories/edit.html.erb
<div class="container" style="text-align: left">
	<div class="row">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/index.html.erb
<div class="container">	
	<div class="row" style="text-align: center">
		<%= link_to 'Back to Contents', contents_path %>
		&nbsp;|&nbsp;
		<%= link_to 'New Category', new_category_path %>
	</div>
	<% totalCategories = 0 %>
	<% @categories.each do |category| %>
		<% next if category.id == 1 %>
		<% if totalCategories == 0 %>
			<style>
				table {
					display: inline-block;
				}

				table th, table td {
					border: 1px solid #ccc;
					padding: 5px;
					text-align: left;
				}
			</style>
			<div class="row" style="margin-top: 8px">
				<table>
					<tr>
						<th>ID</th>
						<th>Text</th>
						<th>Action</th>
					</tr>
		<% end %>
		<tr>
			<td><%= category.id %></td>
			<td><%= category.text %></td>
			<td>
				<%= link_to 'Edit', edit_category_path(category) %>
				&nbsp;|&nbsp;
				<%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</tr>
	<% 	totalCategories += 1 %>
	<% end %>
	<% if totalCategories == 0 %>
		<div 
			class="row" 
			style="
				background-color: #ccc;
				margin-top: 8px;
				padding: 5px
			"
		>
			<div class="col-md-12">No category found.</div>
		</div>
	<% else %>
			</table>
		</div>
	<% end %>
</div>

app/views/categories/new.html.erb
<div class="container" style="text-align: left">
	<div class="row">
		<%= render 'form' %>
	</div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<div class="row" style="text-align: center">
		<%= link_to 'Back', categories_path %>
	</div>
	<div 
		class="row" 
		style="margin-top: 8px"
	>
		<style>
			table {
				display: inline-block;
			}

			table th, table td {
				border: 1px solid #ccc;
				padding: 5px;
				text-align: left;
			}
		</style>		
		<table>
			<tr>
				<th>ID</th>
				<th>Text</th>
			</tr>
			<tr>
				<td><%= @category.id %></td>
				<td><%= @category.text %></td>
			</tr>
	</div>	
</div>

app/views/contents/_form.html.erb
<% if @content.errors.any? %>
	<% @content.errors.full_messages.each do |errMsg| %>
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>Error!</strong>&nbsp;<%= errMsg %>
		</div>
	<% end %>
<% end %>
<%= form_for @content, :html => { :class => "form-horizontal" } do |f| %>
	<fieldset>
		<div class="form-group">
			<%= f.label :title, class: "control-label" %>
			<%= f.text_field :title, class: "form-control", placeholder: "Content title" %>	
		</div>
		<div class="form-group">
			<%= f.label :subtitle, class: "control-label" %>
			<%= f.text_field :subtitle, class: "form-control", placeholder: "Content subtitle" %>	
		</div>
		<div class="form-group">
			<%= f.label :category_id, class: "control-label" %>
			<%= collection_select(:content, :category_id, @categories.all, :id, :text, {}, { class: "form-control" } ) %>
		</div>
		<div class="form-group">
			<%= f.label :text, class: "control-label" %>
			<%= f.text_area :text, class: "form-control", placeholder: "Content text" %>	
		</div>
		<div class="form-group" style="text-align: right">
			<%= f.submit class: "btn btn-primary" %>
			<%= link_to "Cancel", contents_path, { class: "btn btn-default" } %>
		</div>
	</fieldset>
<% end %>

app/views/contents/edit.html.erb
<div class="container" style="text-align: left">
	<div class="row">
		<%= render 'form' %>
	</div>
</div>

app/views/contents/index.html.erb
<div class="container">	
	<div class="row" style="text-align: center">
		<%= link_to 'New Content', new_content_path %>
		&nbsp;|&nbsp;
		<%= link_to 'Edit Categories', categories_path %>
	</div>
	<div class="row" style="text-align: center">
		<strong>Filter category:&nbsp;</strong>
		<%= link_to 'All', contents_path %>&nbsp;
		<% @categories.each do |category| %>
			<%= link_to category.text, "#{contents_path}?category_id=#{category.id}" %>&nbsp;
		<% end %>
	</div>
	<% totalContents = 0 %>
	<% @contents.each do |content| %>
		<div 
			class="row" 
			style="						
				margin-top: 8px;
				text-align: left				
			"
		>			
			<div class="col-md-12" style="padding: 0px; text-align: right"><%= link_to 'Edit', edit_content_path(content) %>&nbsp;|&nbsp;<%= link_to 'Delete', content_path(content), method: :delete, data: { confirm: 'Are you sure?' } %></div>
			<div 
				class="col-md-12" 
				style="
					background-color: #ccc;
					padding: 5px
				"
			>
				<span style="font-weight: bolder"><%= content.title %></span>
				<br/>
				<span><%= content.subtitle %></span>
				<br/><br/>
				<strong>Category:&nbsp;</strong>
				<% @categories.each do |category| %>
					<% if category.id == content.category_id %>
						<%= category.text %>
						<% break %>
					<% end %>
				<% end %>
			</div>			
			<div 
				class="col-md-12" 
				style="
					border: 1px solid #ccc;
					padding: 5px
				"
			><%= content.text %></div>
		</div>
	<% 	totalContents += 1 %>
	<% end %>
	<% if totalContents == 0 %>
		<div 
			class="row" 
			style="
				background-color: #ccc;
				margin-top: 8px;
				padding: 5px
			"
		>
			<div class="col-md-12">No content found.</div>
		</div>
	<% end %>
</div>

app/views/contents/new.html.erb
<div class="container" style="text-align: left">
	<div class="row">
		<%= render 'form' %>
	</div>
</div>

app/views/contents/show.html.erb
<div class="container">
	<div class="row" style="text-align: center">
		<%= link_to 'Back', contents_path %>
	</div>
	<div 
		class="row" 
		style="						
			margin-top: 8px;
			text-align: left				
		"
	>		
		<div 
			class="col-md-12" 
			style="
				background-color: #ccc;
				padding: 5px				
			"
		>
			<span style="font-weight: bolder"><%= @content.title %></span>
			<br/>
			<span><%= @content.subtitle %></span>
			<br/><br/>
			<strong>Category:&nbsp;</strong>
			<% @categories.each do |category| %>
				<% if category.id == @content.category_id %>
					<%= category.text %>
					<% break %>
				<% end %>
			<% end %>
		</div>			
		<div 
			class="col-md-12" 
			style="
				border: 1px solid #ccc;
				padding: 5px
			"
		><%= @content.text %></div>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iskandar Malaysia - Rails Training</title>
  <!-- JQuery Component -->
  <script src="/libraries/jquery/jquery-2.0.3.min.js"></script>
  <!-- End -->
  <!-- Twitter Bootstrap Component -->
  <link rel="stylesheet" href="/libraries/bootstrap-3.0.3/css/bootstrap.min.css">
  <script src="/libraries/bootstrap-3.0.3/js/bootstrap.min.js"></script>
  <!-- End -->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="contents">
		<div class="container">
			<div class="row">
				<h1>Iskandar Malaysia</h1>
			</div>
			<div class="row">
				<h4>Rails Training</h4>
			</div>
			<div class="row">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>